/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MockVotingVaultInterface extends utils.Interface {
  functions: {
    "queryVotePower(address,uint256,bytes)": FunctionFragment;
    "setVotingPower(address,uint256)": FunctionFragment;
    "votingPower(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "queryVotePower",
    values: [string, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingPower",
    values: [string, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "votingPower", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "queryVotePower",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingPower",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPower",
    data: BytesLike,
  ): Result;

  events: {};
}

export interface MockVotingVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockVotingVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    queryVotePower(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    "queryVotePower(address,uint256,bytes)"(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    setVotingPower(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    "setVotingPower(address,uint256)"(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    votingPower(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "votingPower(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;
  };

  queryVotePower(
    _user: string,
    blockNumber: BigNumberish,
    arg2: BytesLike,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  "queryVotePower(address,uint256,bytes)"(
    _user: string,
    blockNumber: BigNumberish,
    arg2: BytesLike,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  setVotingPower(
    _user: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  "setVotingPower(address,uint256)"(
    _user: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  votingPower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "votingPower(address)"(
    arg0: string,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  callStatic: {
    queryVotePower(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "queryVotePower(address,uint256,bytes)"(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setVotingPower(
      _user: string,
      _amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setVotingPower(address,uint256)"(
      _user: string,
      _amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    votingPower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "votingPower(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    queryVotePower(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "queryVotePower(address,uint256,bytes)"(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setVotingPower(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    "setVotingPower(address,uint256)"(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    votingPower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "votingPower(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    queryVotePower(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "queryVotePower(address,uint256,bytes)"(
      _user: string,
      blockNumber: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    setVotingPower(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    "setVotingPower(address,uint256)"(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    votingPower(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "votingPower(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
