/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MockCoreVotingInterface extends utils.Interface {
  functions: {
    "approvedVaults(address)": FunctionFragment;
    "setVault(address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approvedVaults",
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [string, boolean],
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedVaults",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;

  events: {};
}

export interface MockCoreVoting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockCoreVotingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approvedVaults(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "approvedVaults(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    setVault(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    "setVault(address,bool)"(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  approvedVaults(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "approvedVaults(address)"(
    arg0: string,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  setVault(
    vault: string,
    what: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  "setVault(address,bool)"(
    vault: string,
    what: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    approvedVaults(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "approvedVaults(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    setVault(
      vault: string,
      what: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setVault(address,bool)"(
      vault: string,
      what: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approvedVaults(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "approvedVaults(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setVault(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    "setVault(address,bool)"(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approvedVaults(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "approvedVaults(address)"(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    setVault(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    "setVault(address,bool)"(
      vault: string,
      what: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
