/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ReadAndWriteAnyStorageInterface extends utils.Interface {
  functions: {
    "readStorage(uint256)": FunctionFragment;
    "writeStorage(uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "readStorage",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "writeStorage",
    values: [BigNumberish, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: "readStorage",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeStorage",
    data: BytesLike,
  ): Result;

  events: {};
}

export interface ReadAndWriteAnyStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReadAndWriteAnyStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    readStorage(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string] & { data: string }>;

    "readStorage(uint256)"(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string] & { data: string }>;

    writeStorage(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    "writeStorage(uint256,bytes32)"(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  readStorage(slot: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "readStorage(uint256)"(
    slot: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  writeStorage(
    slot: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  "writeStorage(uint256,bytes32)"(
    slot: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    readStorage(slot: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "readStorage(uint256)"(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    writeStorage(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    "writeStorage(uint256,bytes32)"(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    readStorage(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "readStorage(uint256)"(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    writeStorage(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    "writeStorage(uint256,bytes32)"(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    readStorage(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "readStorage(uint256)"(
      slot: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    writeStorage(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    "writeStorage(uint256,bytes32)"(
      slot: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
